### ISSUE TITLE
Backport of minimal requirements to OrientDB 1.7.x

### ISSUE THREAD

**Issue by vidakovic** [orientechnologies/spring-data-orientdb#12]
The low level APIs (ODatabase etc.) changed in the new OrientDB 2.x release. This affects the connection pool classes. The connection pool class for ODatabaseDocument changed (was ODatabaseDocumentPool, is OPartitionedDatabasePool); the new one doesn't share any common interface with the ones for OObjectDatabasePool.

@sleroy expressed need for this.

**Comment by robfrank** [comment]
old stuff.
