### ISSUE TITLE
Provide a configuration parameter to trigger the database schema creation/update.

### ISSUE THREAD

**Issue by sleroy** [orientechnologies/spring-data-orientdb#18]
That's a matter of opinion, I would prefer to be able to activate/desactivate the behaviour implemented in the [AbstractOrientFactory](https://github.com/vidakovic/spring-data-orientdb/blob/master/spring-data-orientdb-commons/src/main/java/org/springframework/data/orient/commons/core/AbstractOrientDatabaseFactory.java). 
This behaviour creates conditionaly a database if we have provided a *non remote* url.

My proposal is : 
- remove the condition for *non remote* url. That's confusing why I cannot create automatically remote databases (in hibernate I may do it with create-drop features and with the right jdbc url).
- replace the condition with a configuration parameter (i.e allowAutocreateDatabase).

**Comment by vidakovic** [comment]
@sleroy I've added a new property "autoCreate" to AbstractOrientDatabaseFactory. If it's not set (=null) then only non-remote databases will be automatically created. If the property is set (via Spring config/xml) then the default behaviour is overridden.

Changes are part of PR #22.
