### ISSUE TITLE
Spring Data for OrientDB

### ISSUE THREAD

**Issue by Archana14** [orientechnologies/spring-data-orientdb#24]
Hi 
I want to use Spring Data for OrientDB. But it seems its in a implementation Phase.I am using Graph database in my Application. It will be good to have Spring data for OrientDB. Could please let me know when it will available or Could you suggest best option other than Spring data.

**Comment by CasperCLD** [comment]
I would like to know this too. Is this production ready? @lvca

**Comment by vidakovic** [comment]
@Archana14 @CasperCLD no, it's not production ready yet. FYI: I will spend some time this weekend to update to the latest version of OrientDB. There is especially one task I'd like to finish: Jooq is used to parse SQL statements... now that OrientDB (at least the develop branch) has a Javacc based SQL parser it would be nice to drop that dependency.

Other than that there is just a lack of unit tests to make further assumptions.

Nevertheless, I will use it in production. Once I have more metrics with that I can report back (please ping me if it takes too long).

**Comment by mkalus** [comment]
I'm also interested in using this repository in a project of mine. Do you know when we could actually test it with Orient 2.0.x?

**Comment by Lorkster** [comment]
Is this project proceeding at all?

**Comment by ancore** [comment]
Would be possible to use when my pull-request goes through.

**Comment by maku** [comment]
would also be interested if it is advisable to use this ???

**Comment by ctientcheu** [comment]
Hello @vidakovic  

Any update on where you stand with the metrics and "readiness" of this component?

**Comment by compensator** [comment]
This appears to have been abandoned.  I cloned the repo and analyzed the state of this code and examples during May.  After executing the Apache Shiro sample application, I began fixing the Object interface which is the area that is incomplete and fails.  After a few modifications it is close, but I didn't have any more time to apply.  I may have some time late this week to work on this.

**Comment by lvca** [comment]
@compensator Thanks for contributing on it, I'm waiting for your PR.

**Comment by pires** [comment]
@compensator any updates?

**Comment by compensator** [comment]
My hope was to have time at the end of that week to work on this.  That didn't happen.  I can say that after my review of the code in more depth, I might try a slightly different tactic.  After I finish some the code I've been working on (related to OrientDB), I'll try to return to this.

**Comment by eugene-kamenev** [comment]
Guys if you are using groovylang in your spring projects, take a look at my work: [orientdb-groovy](https://github.com/eugene-kamenev/orientdb-groovy)

**Comment by compensator** [comment]
@eugene-kamenev  It looks solid.  All solution pathways are on the table.

I looked at this when the developers on my team complained about not being able to take advantage of an annotations-based persistence framework for OrientDB that would manage transactions for them.  I, myself, moved to using Tinkerpop Frames combined with the OrientDB Graph API and my own persistence management class.  I may give Ferma a shot eventually and am watching Peapod as well.

The members of my team who prefer to use Spring Boot, will be referred to your project.

**Comment by saljuama** [comment]
I'd like to contribute to get OrientDB on the train of Spring Data, i'll clone the repository and navigate it to get familiar with it. 

First things first, do i need to sign a CLA? and, could you give any pointers on would be the most needed features right now to get this project going?

**Comment by lvca** [comment]
@saljuama Welcome aboard. You need to sign the clahub only at your first Pull Request ;-)

**Comment by TeamXceleratorDev** [comment]
Using latest version, I am still getting Maven build errors below when trying to run the Hello sample. 

Failed to execute goal on project spring-boot-orientdb-hello: Could not resolve dependencies for project org.springframework.boot.samples:spring-boot-orientdb-hello:jar:0.10.0-SNAPSHOT: Could not find artifact org.springframework.boot:spring-boot-orientdb-autoconfigure:jar:0.10.0-SNAPSHOT in nexus

**Comment by ritesh0919** [comment]
Hello,

Any update on this project. Is 0.11 release production ready for Graph APIs?
I am using Graph model in my project and looking for GraphAPIs rather than Document or Object. Looks like there are some missing pieces.

**Comment by lvca** [comment]
We have users that use this in production, but use the develop branch please. However, we found resources to provide official support for this module in the next months.

**Comment by ritesh0919** [comment]
Thanks @lvca for the response. 
I got the develop branch but I see Graph implementation using Document APIs to do any operations on OrientDB. That being said, when I use a Person object and PersonRepository (as shown in spring-data-orient-hello sample) implementing GraphRepository, Person object is getting created as a document rather than schema full Person vertex. 
I was expecting Graph implementation to use OrientGraph object instead of ODocumentXXX. 
I am sure, I am missing something here. Is there a hello sample project for Graph APIs?

**Comment by robfrank** [comment]
I'm the new maintainer of the project. I close this issue for now.
