### ISSUE TITLE
Project no longer compiles and runs

### ISSUE THREAD

**Issue by TeamXceleratorDev** [orientechnologies/spring-data-orientdb#40]
As part of recent promotions to Master, the code does not complete a Maven clean build.  The reason is that the Shiro example is failing.  Also, the promotion to Master was not done through the Develop branch first.  As a result, Master and Develop are now out-of-sync.  Develop doesn't have changes from Master.  Attached is the console log showing the error.  Thankfully, I have an older copy backed up which I am currently using.  I would suggest reverting the recent changes, and having them first merged into Develop and tested, before promoting to Master.

[orient-spring.txt](https://github.com/orientechnologies/spring-data-orientdb/files/195678/orient-spring.txt)

**Comment by RAndrews137** [comment]
I was able to get it to work with latest Develop code, but that was using a compile first and not pulling Maven artifacts.  The code between Develop and Master still needs to merged.

**Comment by robfrank** [comment]
i merged all and created a new branch 2.2.x, where the branch name is related to the OrientDB's version used. The develop branch uses the 3.0.0-SNAPSHOT version of OrientDB

**Comment by RAndrews137** [comment]
Thanks Roberto
