### ISSUE TITLE
Maven public repo does not have artifacts

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/spring-data-orientdb#41]
I was not able to find artifacts for spring-data-orientdb under the public maven or spring libs repos.  I currently have to build locally first so the jars will be in my local .m2 repo.  That is not a good solution. Current OrientDB and spring-data-orientdb artifacts should be published to Maven.

**Comment by jbhardwaj12** [comment]
I am not able to build current master, its failing and not creating jars in my local .m2 repo.

**Comment by RAndrews137** [comment]
@jbhardwaj12  Yes, a recent check-in broke the build.  To fix it, just remove the Shiro example.  Then it will compile.

**Comment by jbhardwaj12** [comment]
yes that works. Thanks @RAndrews137

**Comment by robfrank** [comment]
we moved spring data under com.orientechnologies groupId and released:
http://central.maven.org/maven2/com/orientechnologies/

**Comment by RAndrews137** [comment]
Thanks Rob.  I will try it out sometime.  Perhaps later the maven and gradle dependency info can be added to the read-me.  I have seen other projects do that to help jumpstart new users  :)
