### ISSUE TITLE
question: are these libs in any publicly available maven server?

### ISSUE THREAD

**Issue by tony-kerz** [orientechnologies/spring-data-orientdb#45]
i didn't spot them in maven-central, are they somewhere else,
or would we need to build and publish for ourselves to use...?

regards,
tony.

**Comment by lvca** [comment]
The tricky part is that the artifact is spring, so we can't publish it on maven. How does it work with other Spring Data modules?

Should we change the pom.xml?

**Comment by tony-kerz** [comment]
good question luca,

from what i can gather per [the spring-data homepage](http://projects.spring.io/spring-data/) the spring-data guys have accepted certain "community modules" to be part of their "release train".

the benefit of that would be an official-ness to the libraries and they would be cross-advertised from the spring-data home page and documentation,
but their would need to be willingness from you guys and the spring-data guys (@olivergierke ?) to spend whatever energy is required to curate that relationship.

other options to consider: 

(1) i've spent many years working with maven, but i've never published anything to maven-central, but you would probably know if
it's possible to keep the maven coordinates the same, and just publish them to maven-central yourself,

```
<groupId>org.springframework.data</groupId>
<artifactId>spring-data-orientdb-commons</artifactId>
```

(2) use your own group-id, something like:

```
<groupId>com.orientechnologies.data</groupId>
<artifactId>spring-data-orientdb-commons</artifactId>
```

regards,
tony.

**Comment by carlspring** [comment]
Hi,

When will these be available via Maven Central, or Spring's repositories?

**Comment by AlexOreshkevich** [comment]
Hi guys, 

we would like to consume that spring-data repo through public Maven repository. By the way, is it stable? I was trying to build it locally, but there was failing tests.

Do you have some roadmap and predictable time terms for the release of this project?

**Comment by carlspring** [comment]
I have experience with deploying to Maven Central, where I'm hosting a number of my [libraries](http://repo1.maven.apache.org/maven2/org/carlspring/) and, mainly, [Maven Plugins](http://repo1.maven.apache.org/maven2/org/carlspring/maven/).

I have no problem sorting this out and getting it to deploy to Maven Central, if you've already got credentials for it. Here's a detailed answer I wrote on [Stackoverflow](http://stackoverflow.com/questions/15876211/how-to-opensource-a-maven-plugin/15876923#15876923) a while ago, which, I believe, is still accurate.

Let me know, if and how I could help get it into Maven Central. Alternatively, if you have a CI server like Jenkins, I could get it set up to deploy as necessary, (I'm a senior build and release engineer).

**Comment by steve-todorov** [comment]
We're also using your project in our codebase and we've had to fork it and deploy it into our own repository manager in order to be able to use it. It would be great to finally see this as an official release we can resolve as a dependency from somewhere.

**Comment by robfrank** [comment]
We changed the groupdID  to be able to release them, and even snapshots are on sonatype
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/

**Comment by lvca** [comment]
Hey guys,
No answer from Pivotal :-(, so I decided to publish it under OrientDB: https://github.com/orientechnologies/spring-data-orientdb/tree/develop.
