### ISSUE TITLE
question: is it possible to interact with embedded documents?

### ISSUE THREAD

**Issue by tony-kerz** [orientechnologies/spring-data-orientdb#47]
i took this library for a spin, and it seems to be ok for the basic case so far.

as usual, when integrating real requirements, basic morphs to "less-basic".

i'm trying to use [the recent spatial feature](http://orientdb.com/docs/2.2/Spatial-Module.html),
in such a way that a domain object like a `Person` for instance would have a `location` which i guess would manifest as an embedded document.

so, i would want to save and query on domain objects having embedded documents of type `OPoint`.

it's not obvious to me how to make that happen with this library, is it possible?

if not, i would be happy to attempt a pull-request with some guidance around what would need to happen.

best,
tony.

**Comment by lvca** [comment]
Hey @maggiolo00 could you please help @tony-kerz on this, so he can contribute with a PR?

**Comment by maggiolo00** [comment]
@lvca 
i sure never used this module but i can try to help @tony-kerz to integrate GEO stuff.
From what i saw it could be done like spring-data-mongo

http://docs.spring.io/spring-data/data-mongo/docs/1.9.1.RELEASE/reference/html/#mongo.geo-json

**Comment by lvca** [comment]
@tony-kerz any interest for a PR?
