### ISSUE TITLE
OrientGraphRepository throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ohaionm** [orientechnologies/spring-data-orientdb#48]
I have a repository extends OrientGraphRepository and when I have a query that should return zero results, it throws "IndexOutOfBoundsException". If you will run the shiro example and query for user by email, in case that there is no such user the exception will be thrown.
That's the basics so I am wondering if this project is recommended for production. It's really simplifying development and I wish to use it, but I need to know if it's stable enough.

**Comment by RAndrews137** [comment]
@robfrank    This is related to AbstractOrientOperations Line#569.  It is using get(0) without checking for an empty list first.  Recommend size check first and then decide what to return when there is no result (null?).

**Comment by robfrank** [comment]
fixed, now the method returns null if the result set is empty

**Comment by RAndrews137** [comment]
Sounds good.  Thanks
