### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/spring-data-orientdb#50]
We are trying to use Spring-Data-Orient with Gradle.  The current documentation is only for Maven and 0.11 release.  The current code is for 0.12-SNAPSHOT.  Can you please add Gradle dependency documentation and also update artifacts for 0.12?  We are seeking to use it right away.

**Comment by robfrank** [comment]
I added indication on the readme.md of 2.2.x branch:

https://github.com/orientechnologies/spring-data-orientdb/tree/2.2.x

I hope they are good, since I'm not a gradle's  user

**Comment by RAndrews137** [comment]
Thanks Roberto.  We will have someone try out these changes within a day or two and let you know how it goes.  Thank you very much   :)
