### ISSUE TITLE
DetachAll Property

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/spring-data-orientdb#54]
@robfrank 

In earlier testing, I noticed an issue where a runtime exception would occur if the model entity Java classes did not have a DetachAll property.  I resolved it by adding it and even contributed it back via the Hello example.  However, it would better if the code did not require this property in the model Java classes.  Can you please double-check the usage of DetachAll and see where it might be used?

**Comment by robfrank** [comment]
I'll check il the Detach annotation on repository can avoid the detachAll method on domain objects
