### ISSUE TITLE
countBy method with annotated query fails

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/spring-data-orientdb#58]
If you create a countBy method and include an annotated query, it will throw an exception.  The reason is that the isCountBy returns false when trying to determine which QueryExecution to use.  When an annotated query is used, the StringBasedOrientQuery is used.  That has a countBy boolean flag.  However, it is not getting set to true if the method name startsWith 'countBy'.

I have already created a fix for this issue and tested that it works.  I will check it in today and submit a pull request.

**Comment by robfrank** [comment]
this commit: https://github.com/orientechnologies/spring-data-orientdb/commit/d5cf6ecfab43a9f6446190283c4f25a4661b00d6

shows how to annotate a query to be used as count query.

**Comment by RAndrews137** [comment]
Excellent.  Thanks Roberto  :)
