### ISSUE TITLE
Factory - DB Pool Settings Ignored

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/spring-data-orientdb#59]
While running BDD tests, we repeatedly experienced an issue where they tests were getting stuck.  While investigating, it appears that the code is unable to acquire a connection.  We tried increasing the max pool settings for the Factory class, but it did not work.  After even more investigation, we found what appears to be a bug.  The AbstractOrientDatabaseFactory class has the min and max pool settings.  However, the code is not using them!   Listed below are the changes recently to:  OrientObjectDatabaseFactory.  You will notice that the pool.setup() call was removed.  The code is now defaulting to the number of processors within OPartitionedDatabasePool.  So even if we try to increase the pool size, it is not using it.  This was introduced in the 0.12 release of OSD.  If the change was intentional, please explain.  Currently, our BDD tests are getting stuck.  Can someone please take a look and release the fix as part of the 0.13 release? 

Thanks,
Ronnie

@Override
      protected void createPool() {
 -        pool = new OObjectDatabasePool(getUrl(), getUsername(), getPassword());
 -        pool.setup(minPoolSize, maxPoolSize);
 +        pool = new OPartitionedDatabasePool(getUrl(), getUsername(), getPassword());
 +
 +
      }

**Comment by RAndrews137** [comment]
I did some more reading through OPartitionedDatabasePool, and it appears that maxPartitionSize is never used.  The number of pool partitions is hard-coded at 2.  Not sure if that was intentional or not.  I believe that when the pool is created, it is using 2 partitions with 2 db connections per partition.  I am still reading through the code trying to understand the pool better.

**Comment by RAndrews137** [comment]
My mistake, maxPartitonSize is being used.

**Comment by lvca** [comment]
@RAndrews137 so if you allocate a larger pool it works?

**Comment by robfrank** [comment]
@RAndrews137  did you solve the issue?

**Comment by RAndrews137** [comment]
No, the bug still exists.  As mentioned in the original description, the pool sizes are no longer being set.  That was introduced in the 0.12 release.  The line of code below was removed from OrientObjectDatabaseFactory.   I think that it should be added back unless it was removed for a very good reason.  Currently, trying to set the pool size in OSD does not work because this line was removed.

pool.setup(minPoolSize, maxPoolSize);

**Comment by robfrank** [comment]
My colleague is fixing an issue on the pool, we will release 2.2.9 in a couple of day and then move spring data on it (and maybe release 0.13)

**Comment by RAndrews137** [comment]
OK.  Hopefully the description made sense regarding pool sizings.  I will inform our team to expect a new release in the near future.  Thanks.  Please let me know if you have any questions  :)

**Comment by RAndrews137** [comment]
The reason why we were experiencing an issue with the BDD tests is because SpringBoot uses Tomcat.  Tomcat has a poo of threads (I think default is 200 threads).  The current Orient pool uses ThreadLocal which means each thread grabs a connection and decrements a semaphore counter.  The issue we ran into was a deadlock because Tomcat does not close threads from its pool after they perform work. Thus, the listener for thread termination was never releasing connections.  Since Tomcat's thread settings were so high, it could easily exhaust the Orient DB pool.  Took several hours of debugging to figure it out.  I understand the use of ThreadLocal for high performance, but users must ensure the Orient connection pool is equal or larger to the amount concurrent threads (includes case like Tomcat which doesn't kill threads).  Due to the defect in 0.12, we were not able to increase the Orient pool max size to adjust.  I hope that made sense LOL.  Please let me know if you had any questions.

**Comment by RAndrews137** [comment]
Thanks @robfrank .  We will try it out later today or Monday and let you know  :)
