### ISSUE TITLE
Database connection pool is not using the maxPoolSize

### ISSUE THREAD

**Issue by RAndrews137** [orientechnologies/spring-data-orientdb#61]
With recent testing, we are still seeing cases where the db pool is getting exhausted even after increasing the max pool size.  This issue is in OrientObjectDatabaseFactory.java.  It is using the constructor for OPartitionedDatabasePool which does not use maxPartitionSize or maxPoolSize.  Those are getting set to defaults which is based on the number of processors on the system.

Suggested change is:

@Override
    protected void createPool() {
        
        if (this.maxPoolSize > 0) {
            //since max pool size was set, use it to create the partitioned pool
            pool = new OPartitionedDatabasePool(getUrl(), getUsername(), getPassword(), 
                Runtime.getRuntime().availableProcessors(), this.maxPoolSize);          
        } else {
            //use default max partition size and default max pool size 
            pool = new OPartitionedDatabasePool(getUrl(), getUsername(), getPassword());
        }
    }

**Comment by RAndrews137** [comment]
Hi,

Any updated on this issue @robfrank and @lvca ?  If you would like, I can make the proposed change and submit it as a pull request.  

Thanks

**Comment by RAndrews137** [comment]
I tested today using latest code, and it seems fixed.  I noticed the use of ThreadLocal seems to have been removed.  If that is true, it is probably good.  The ThreadLocal was a challenge in high-thread pool servers like Tomcat which defaults to 200.  Question: if the ThreadLocal logic has been removed, then how are connections returned back to the pool ?

**Comment by RAndrews137** [comment]
Update:  I see that those part of ThreadLocal was removed from OSD, it is still in OPartitionedDatabasePool.  OK.

**Comment by robfrank** [comment]
The connections are returned back to the pool by the TransactionManager. I think we can avoid the threadlocal on the factory, I can get rid of it, and if you can test in a real environment and confirm that all works fine, I will be happy.

**Comment by RAndrews137** [comment]
Yes, I saw that today.  It is performing a close after each request.  We would be happy to help with testing, but due to Gradle dependencies, we can only test once the release has been made so we can pick up the 0.14 artifacts.  At least the pool size issue seems fixed.

**Comment by robfrank** [comment]
Ok, I can release 0.14rc1 without the Threadlocal

**Comment by RAndrews137** [comment]
Perfect  :)

**Comment by robfrank** [comment]
released 0.14rc1, let me know if all works fine, thanks

**Comment by RAndrews137** [comment]
Thanks.  We will try it out today.

**Comment by robfrank** [comment]
how is it going? If it is ok I can release 0.14 on Friday, WDYT?

**Comment by RAndrews137** [comment]
Hi, sorry.  We were not able to test it last week.  We will test 0.14rc1 soon.  Hopefully today and let you know.  Thanks  :)

**Comment by RAndrews137** [comment]
We conducted testing and everything is looking good with 0.14 changes.  I will now close this issue.    Thank you very much for your help.
