### ISSUE TITLE
AbstractOrientOperations hang on multithread workload

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/spring-data-orientdb#62]
Every method on AbstractOrientOperations doesn't close the database instance after the operation, so the db instance isn't returned  to the underlying pool:
```
    @Override
    public <S extends T> S save(S entity) {

        ODatabase<T> db = dbf.db();

        S saved = db.save(entity);

        return saved;
    }

``` 

should be

```
    @Override
    public <S extends T> S save(S entity) {

        ODatabase<T> db = dbf.db();

        S saved = db.save(entity);

        db.close();
        return saved;
    }

```

**Comment by lvca** [comment]
I think it should be:

```
@Override
    public <S extends T> S save(S entity) {
        ODatabase<T> db = dbf.db();
        try{
          S saved = db.save(entity);
        } finally {
          db.close();
        }
        return saved;
    }
```

In this way there can't be a leak in case of exception.

**Comment by robfrank** [comment]
After a deeper code review, I discovered that all is working fine under spring/spring-data. The transaction manager takes care of the lifecycle and calls the close after all objects are correctly serialized to the client (e.g. json).
The drawback is that it is quite impossible to use the template/operations without a transaction manager in place.
