### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jackmatt2** [orientechnologies/spring-data-orientdb#69]
I am comparing Neo4J vs OriendDB and spring-data integration is a must.  This repo looks like it has not been touched in some time.  Is there any plans to revive it or is there an alternative out there?

**Comment by robfrank** [comment]
Hi, I'm the maintainer and I will release in a week some updates.

**Comment by RAndrews137** [comment]
Just checking in regarding @robfrank comment.  Is a new release available?

**Comment by marteloudini** [comment]
hey, im very interesting for your API but i dont know if ready to go production ? 

plz dont let down this project. 

thanks

**Comment by lvca** [comment]
Don't worry, this is part of the official supported plugins. @robfrank is updating it to be compliant with the upcoming 3.0m2, then it will evolve together with v3.0.

**Comment by jackmatt2** [comment]
@lvca But the version is `0.10.0-SNAPSHOT` which means it has never actually been officially released.

**Comment by robfrank** [comment]
hi, we release from branches: 2.2.x and develop are active branches. 
As you can check on maven central, we have a 0.14rc1 out: 
http://central.maven.org/maven2/com/orientechnologies/spring-data-orientdb-object/
