### ISSUE TITLE
Deployment to public Maven repository

### ISSUE THREAD

**Issue by vidakovic** [orientechnologies/spring-data-orientdb#8]
@sleroy offered help with Bintray.

**Comment by spluv** [comment]
Hello,
Any news from Pivotal ?

**Comment by pires** [comment]
Any updates on this?

**Comment by deepthought42** [comment]
Any updates on this?

**Comment by lvca** [comment]
Hi guys,

Days ago I opened a question on the forum, but no answer so far. I can't find any link or contact to send OrientDB as candidate to be included in the official implementations. Anybody has any advice for that?

**Comment by robfrank** [comment]
for the time being, we are releasing under orient gorupId. Shoul investigate how to be part of spring-data
